// Transiciones reales en PostgreSQL sintético: revisión, comentario y cierre.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
const prof='00000000-0000-0000-0000-000000000021',alumno='00000000-0000-0000-0000-000000000022';
const admin='00000000-0000-0000-0000-000000000023',aviso='00000000-0000-0000-0000-000000000024';
const devuelto='00000000-0000-0000-0000-000000000025';
const programado='00000000-0000-0000-0000-000000000027';
const db=new PGlite();
const q=async(sql,params=[])=>(await db.query(sql,params)).rows;
const sesion=async(id,aal='aal2')=>db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('audit.aal',$2,false)",[id,aal]);
const crear=async id=>{
  await db.query(`insert into tutor_anuncios(id,autor_id,tenant,ramos_siglas,modalidad,ubicacion,precio_clp,descripcion,contacto_tipo,contacto_valor,titulo)
    values($1,$2,'uc',array['TEST100'],'individual','online',10000,'Descripción sintética de más de veinte caracteres','whatsapp','56900000000','Clase ficticia')`,[id,prof]);
  await db.query('insert into anuncio_campanas(anuncio_id,dias,tope_clp) values($1,10,50000)',[id]);
  await db.query("update tutor_anuncios set estado='en_revision' where id=$1",[id]);
};
(async()=>{try{
  await db.exec(read('bin/supabase-stubs.sql'));
  await db.exec(`create function auth.jwt() returns jsonb language sql stable as $$
    select jsonb_build_object('aal',coalesce(current_setting('audit.aal',true),'aal1')) $$;
    create table public.user_ramos(user_id uuid);`);
  for(const f of ['clases_particulares','admin_clases','administradores'])await db.exec(read('supabase/'+f+'.sql'));
  await db.query('insert into auth.users(id) values($1),($2),($3)',[prof,alumno,admin]);
  await db.query('insert into admin.administradores(user_id) values($1)',[admin]);
  await db.query('insert into user_ramos values($1)',[alumno]);
  await db.query(`insert into tutor_perfiles(user_id,nombre_publico,presentacion,estado,revisado_at)
    values($1,'Profesor sintético','Experiencia ficticia para probar comportamiento','aprobado',now())`,[prof]);
  await crear(aviso);await crear(devuelto);await crear(programado);
  const flyer=`${prof}/${devuelto}/00000000-0000-0000-0000-000000000026.jpg`;
  await db.query('update tutor_anuncios set flyer_path=$2 where id=$1',[devuelto,flyer]);
  await db.query("insert into storage.objects(bucket_id,name,owner) values('tutor-flyers',$1,$2)",[flyer,prof]);
  await db.exec('grant select on storage.objects to authenticated');

  await sesion(admin,'aal1');
  assert.equal((await q('select flyer_revision_admin_visible($1) as ok',[flyer]))[0].ok,false);
  await db.exec('set role authenticated');
  assert.equal((await q('select name from storage.objects where name=$1',[flyer])).length,0);
  await db.exec('reset role');
  await sesion(admin);
  assert.equal((await q('select flyer_revision_admin_visible($1) as ok',[flyer]))[0].ok,true);
  await db.exec('set role authenticated');
  assert.equal((await q('select name from storage.objects where name=$1',[flyer])).length,1);
  await db.exec('reset role');
  await sesion(alumno);
  assert.equal((await q('select flyer_revision_admin_visible($1) as ok',[flyer]))[0].ok,false);

  await sesion(alumno);
  await assert.rejects(q('select admin_publicar_anuncio($1)',[aviso]),/sin acceso/);
  await sesion(admin,'aal1');
  await assert.rejects(q('select admin_devolver_anuncio($1,$2)',[devuelto,'Corrige el contacto de la clase.']),/sin acceso/);
  await sesion(admin);
  await assert.rejects(q('select admin_devolver_anuncio($1,$2)',[devuelto,'corto']),/10 a 1000/);
  assert.equal((await q('select estado from tutor_anuncios where id=$1',[devuelto]))[0].estado,'en_revision');
  assert.equal((await q('select admin_devolver_anuncio($1,$2) as ok',[devuelto,'Corrige el contacto de la clase.']))[0].ok,true);
  assert.equal((await q('select estado from tutor_anuncios where id=$1',[devuelto]))[0].estado,'borrador');
  assert.equal((await q('select flyer_revision_admin_visible($1) as ok',[flyer]))[0].ok,false);
  await sesion(prof);
  assert.equal((await q('select * from comentarios_devolucion_profesor()'))[0].comentario,'Corrige el contacto de la clase.');
  await sesion(alumno);
  assert.equal((await q('select * from comentarios_devolucion_profesor()')).length,0);
  await sesion(admin);
  assert.equal((await q('select admin_publicar_anuncio($1) as ok',[aviso]))[0].ok,true);
  const publicado=(await q('select estado,publicado_at from tutor_anuncios where id=$1',[aviso]))[0];
  assert.equal(publicado.estado,'publicado');
  assert.equal((await q('select count(*)::int as n from admin.anuncio_publicaciones where anuncio_id=$1',[aviso]))[0].n,1);
  await assert.rejects(q('select admin_publicar_anuncio($1)',[aviso]),/solo se publica un anuncio en revisión/);
  await sesion(alumno);await q("select registrar_alcance_anuncio($1,'lista')",[aviso]);
  await sesion(admin);await q('select admin_pausar_anuncio($1)',[aviso]);
  const antes=(await q('select * from costo_campana($1)',[aviso]))[0];
  await sesion(admin,'aal1');
  await assert.rejects(q('select admin_terminar_anuncio_pausado($1,$2)',[aviso,publicado.publicado_at]),/sin acceso/);
  await sesion(admin);
  await assert.rejects(q('select admin_terminar_anuncio_pausado($1,$2)',[aviso,'2000-01-01']),/campaña pausada cambió/);
  assert.equal((await q('select admin_terminar_anuncio_pausado($1,$2) as ok',[aviso,publicado.publicado_at]))[0].ok,true);
  assert.equal((await q('select estado from tutor_anuncios where id=$1',[aviso]))[0].estado,'expirado');
  const despues=(await q('select * from costo_campana($1)',[aviso]))[0];
  assert.equal(despues.vistas,antes.vistas);assert.equal(despues.dias_cobrados,antes.dias_cobrados);
  assert.equal((await q("select count(*)::int as n from admin.acciones where objetivo=$1 and accion in ('publicar_anuncio','terminar_anuncio_pausado')",[aviso]))[0].n,2);
  await assert.rejects(q('select admin_terminar_anuncio_pausado($1,$2)',[aviso,publicado.publicado_at]),/campaña pausada cambió/);
  await q("update anuncio_campanas set inicio='2099-01-01' where anuncio_id=$1",[programado]);
  await q('select admin_publicar_anuncio($1)',[programado]);
  const fechaProgramada=(await q('select publicado_at from tutor_anuncios where id=$1',[programado]))[0].publicado_at;
  await q('select admin_pausar_anuncio($1)',[programado]);
  assert.equal((await q('select admin_terminar_anuncio_pausado($1,$2) as ok',[programado,fechaProgramada]))[0].ok,true);
  assert.equal((await q('select costo_bruto from costo_campana($1)',[programado]))[0].costo_bruto,0);
  await q('select admin_marcar_cobro_publicacion($1,$2,$3,$4)',[aviso,publicado.publicado_at,'deuda',1000]);
  await sesion(prof);
  await q("update tutor_anuncios set estado='borrador' where id=$1",[aviso]);
  await q("update tutor_anuncios set estado='en_revision' where id=$1",[aviso]);
  await sesion(admin);
  await assert.rejects(q('select admin_borrar_anuncio_revision($1)',[devuelto]),/ya no está en revisión/);
  assert.equal((await q('select admin_borrar_anuncio_revision($1) as ok',[aviso]))[0].ok,true);
  assert.equal((await q('select estado from tutor_anuncios where id=$1',[aviso]))[0].estado,'eliminado');
  assert.equal((await q('select count(*)::int as n from admin.anuncio_publicaciones where anuncio_id=$1',[aviso]))[0].n,1);
  assert.equal((await q('select monto_clp from admin.cobros where anuncio_id=$1',[aviso]))[0].monto_clp,1000);
  assert.equal((await q('select vistas from costo_campana($1)',[aviso]))[0].vistas,1);
  await sesion(prof);await db.exec('set role authenticated');
  assert.equal((await q('select id from tutor_anuncios where id=$1',[aviso])).length,0);
  await db.exec('reset role');
  console.log('OK revisión SQL: MFA, publicación, devolución privada, cierre y borrado con historial');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
