const fs=require('fs'),assert=require('node:assert/strict');
const {PGlite}=require('@electric-sql/pglite');
const leer=f=>fs.readFileSync(__dirname+'/../'+f,'utf8');
const db=new PGlite(),q=async(sql,p=[])=>(await db.query(sql,p)).rows;
const ids=Array.from({length:7},(_,i)=>'00000000-0000-4000-8000-'+String(i+1).padStart(12,'0'));
const [admin,a,b,fen,nueva,otro,uai]=ids;
async function sesion(uid,aal='aal1',sid='sesion-1'){
  await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false),set_config('test.aal',$2,false),set_config('test.session',$3,false)",[uid,aal,sid]);await db.exec('set role authenticated');
}
async function crear(tipo='una',publico='uc',opciones=['Uno','Dos']){
  return (await q('select admin_crear_encuesta($1,$2,$3,$4,$5,$5) id',['Pregunta sintética',tipo,opciones,publico,hoy]))[0].id;
}
let hoy;
(async()=>{try{
  await db.exec(leer('bin/supabase-stubs.sql'));
  await db.exec(`alter table auth.users add column created_at timestamptz not null default '2020-01-01';
    create function auth.jwt() returns jsonb language sql stable as $$ select jsonb_build_object('aal',current_setting('test.aal',true),'session_id',current_setting('test.session',true)) $$;
    create table public.profiles(id uuid primary key references auth.users(id),universidad text);
    create table public.user_ramos(user_id uuid);`);
  for(const f of ['clases_particulares','admin_clases','administradores'])await db.exec(leer('supabase/'+f+'.sql'));
  await db.exec(leer('supabase/encuestas.sql'));
  await db.exec(leer('supabase/encuestas.sql')); // Obligatorio: reaplicar dos veces seguidas.
  for(const id of ids)await q('insert into auth.users(id) values($1)',[id]);
  await q('insert into admin.administradores(user_id) values($1)',[admin]);
  for(const id of [a,b,nueva])await q("insert into profiles values($1,'U. Católica · Ingeniería')",[id]);
  await q("insert into profiles values($1,'U. de Chile · FEN')",[fen]);
  await q("insert into profiles values($1,'U. de los Andes')",[otro]);
  await q("insert into profiles values($1,'U. Adolfo Ibáñez')",[uai]);
  await q("update auth.users set created_at=now()+interval '1 second' where id=$1",[nueva]);
  hoy=(await q("select (now() at time zone 'America/Santiago')::date::text hoy"))[0].hoy;
  await sesion(a);await assert.rejects(crear(),/sin acceso/);
  await sesion(admin);await assert.rejects(crear(),/sin acceso/);
  await assert.rejects(q('select admin_encuestas()'),/sin acceso/);
  await sesion(admin,'aal2');const encuesta=await crear();
  await assert.rejects(crear(),/Ya hay una encuesta/);
  await assert.rejects(crear('una','todos'),/Ya hay una encuesta/);
  const efen=await crear('varias','fen');
  const euai=await crear('una','uai',Array.from({length:6},(_,i)=>'Opción '+(i+1)));
  const futuro=(await q("select admin_crear_encuesta('Futura','una',array['Uno','Dos'],'uandes',$1::date+1,$1::date+2) id",[hoy]))[0].id;
  await assert.rejects(q("select admin_crear_encuesta('Vencida','una',array['Uno','Dos'],'uandes',$1::date-2,$1::date-1)",[hoy]),/fechas/);
  await assert.rejects(crear('una','uai',['Solo una']),/2 y 6/);
  await assert.rejects(crear('una','uai',Array.from({length:7},(_,i)=>String(i))),/2 y 6/);
  await assert.rejects(crear('una','uai',['igual','IGUAL']),/2 y 6/);

  await sesion(a);
  assert.deepEqual((await q('select id from encuestas')).map(x=>x.id),[encuesta]);
  await assert.rejects(q('select creado_por from encuestas'),/permission denied/);
  const visita=i=>'00000000-0000-4000-9000-'+String(i).padStart(12,'0');
  const entrar=async i=>(await q('select encuesta_al_entrar($1) r',[visita(i)]))[0].r;
  assert.equal((await entrar(1)).mostrar,true,'cuenta existente no se trata como nueva');
  assert.equal((await entrar(1)).mostrar,false,'no repite en la misma visita');
  assert.equal((await entrar(2)).mostrar,true);
  assert.equal((await entrar(3)).mostrar,false,'máximo dos aperturas');
  await q('select responder_encuesta($1,$2)',[encuesta,[1]]);
  await assert.rejects(q('select responder_encuesta($1,$2)',[encuesta,[1,2]]),/opciones/);
  await q('select responder_encuesta($1,$2)',[encuesta,[2]]);
  assert.equal((await q('select opciones from encuesta_respuestas'))[0].opciones[0],2,'edita una sola fila');
  assert.equal((await entrar(4)).mostrar,false,'no insiste tras responder');
  await assert.rejects(q('select admin_resultados_encuesta($1)',[encuesta]),/sin acceso/);
  await assert.rejects(q('insert into encuesta_respuestas(encuesta_id,user_id,universidad) values($1,$2,$3)',[encuesta,b,'uc']),/permission denied/);
  await sesion(b);assert.equal((await q('select * from encuesta_respuestas')).length,0,'B no lee A');
  await q('select responder_encuesta($1,$2)',[encuesta,[1]]);
  assert.equal((await q('select * from encuesta_respuestas')).length,1,'B sí lee lo suyo');
  await sesion(a);assert.equal((await q('select * from encuesta_respuestas')).length,1,'A tampoco lee B');
  await sesion(fen);assert.equal((await q('select id from encuestas'))[0].id,efen);
  await assert.rejects(q('select responder_encuesta($1,$2)',[encuesta,[1]]),/no está disponible/);
  await q('select responder_encuesta($1,$2)',[efen,[1,2]]);
  await assert.rejects(q('select responder_encuesta($1,$2)',[efen,[1,1]]),/opciones/);
  await sesion(uai);assert.equal((await q('select mi_encuesta_activa() e'))[0].e.id,euai,'público UAI y seis opciones');
  await sesion(otro);assert.equal((await q('select mi_encuesta_activa() e'))[0].e,null,'UAndes no ve una encuesta futura');
  await assert.rejects(q('select responder_encuesta($1,$2)',[futuro,[1]]),/no está disponible/);
  await sesion(nueva);assert.equal(await entrar(5),null,'primera sesión de cuenta nueva');
  assert.equal(await entrar(5),null,'recargar conserva la primera visita');
  assert.equal((await entrar(6)).mostrar,true,'otra visita permite la encuesta sin cerrar sesión de Auth');
  await sesion(admin);await assert.rejects(q('select admin_resultados_encuesta($1)',[encuesta]),/sin acceso/);
  await sesion(admin,'aal2');
  const resultado=(await q('select admin_resultados_encuesta($1) r',[encuesta]))[0].r;
  assert.deepEqual(resultado,{total:2,opciones:[{opcion:'Uno',total:1},{opcion:'Dos',total:1}],textos:[]});
  assert.deepEqual((await q('select admin_resultados_encuesta($1) r',[efen]))[0].r.opciones,[{opcion:'Uno',total:1},{opcion:'Dos',total:1}]);
  assert.equal((await q('select * from encuesta_respuestas')).length,0,'admin tampoco tiene lectura directa de respuestas ajenas');
  await q("select admin_estado_encuesta($1,'pausada')",[encuesta]);
  await sesion(a);assert.equal((await q('select mi_encuesta_activa() e'))[0].e,null);
  await assert.rejects(q('select responder_encuesta($1,$2)',[encuesta,[1]]),/no está disponible/);
  await sesion(admin,'aal2');await q("select admin_estado_encuesta($1,'activa')",[encuesta]);
  await q("select admin_estado_encuesta($1,'terminada')",[encuesta]);
  await q("select admin_estado_encuesta($1,'terminada')",[efen]);
  await q("select admin_estado_encuesta($1,'terminada')",[euai]);
  await q("select admin_estado_encuesta($1,'terminada')",[futuro]);
  const texto=await crear('texto','todos',[]);
  await sesion(a);await q('select responder_encuesta($1,$2,$3)',[texto,[],'Me gustaría esta mejora']);
  await assert.rejects(q('select responder_encuesta($1,$2,$3)',[texto,[],'a'.repeat(281)]),/280/);
  await sesion(b);await q('select responder_encuesta($1,$2,$3)',[texto,[],'Me gustaría esta mejora']);
  await sesion(admin,'aal2');
  assert.deepEqual((await q('select admin_resultados_encuesta($1) r',[texto]))[0].r,{total:2,opciones:[],textos:[{texto:'Me gustaría esta mejora',total:2}]});
  await db.exec('reset role');
  const instalado=(await q('select instalada_at from admin.encuestas_config'))[0].instalada_at;
  await db.exec(leer('supabase/encuestas.sql'));
  assert.equal((await q('select instalada_at from admin.encuestas_config'))[0].instalada_at.getTime(),instalado.getTime());
  assert.equal((await q('select count(*)::int n from encuesta_respuestas'))[0].n,5,'reaplicar conserva respuestas');
  await q('delete from profiles where id=$1',[a]);await q('delete from auth.users where id=$1',[a]);
  for(const tabla of ['encuesta_respuestas','encuesta_visitas','encuestas_cuentas'])assert.equal((await q('select count(*)::int n from '+tabla+' where user_id=$1',[a]))[0].n,0);
  for(const tabla of ['encuestas','encuesta_respuestas','encuesta_visitas','encuestas_cuentas'])assert.equal((await q('select relrowsecurity ok from pg_class where oid=$1::regclass',[tabla]))[0].ok,true);
  await db.exec('set role anon');await assert.rejects(q('select mi_encuesta_activa()'),/permission denied/);
  console.log('OK: SQL reaplicable, MFA real, RLS entre cuentas/públicos, máximo dos, primera sesión, edición, agregados y CASCADE');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
